backend:
  name: git-gateway
  branch: main # Or the branch you want to use

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts" # Folder for blog posts
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }