name: Deploy Astro App

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20  # Use the version required by your Astro app
    
        # Set npm registry to public and clear old configs
    - name: Install dependencies
      run: |
        npm config delete proxy
        npm config delete https-proxy
        npm config delete registry
        npm config set registry https://registry.npmjs.org/ --global
        npm cache clean --force
        npm config list
        npm install --registry=https://registry.npmjs.org/

    # Build the Astro app
    - name: Build Astro app
      run: npm run build

    # Deploy to the FTP server
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: dist/  # Astro's default output directory
        server-dir: /public_html/test/  # Specify your remote folder